### ISSUE TITLE
Clear instructions on how to use the terminal

### ISSUE THREAD

**Issue by willfurnass** [trallard/JNB_reproducible#11]
* Ctrl-Shift-+ to increase the gnome-terminal font size (useful on HiDPI displays)
* Command key (on macOS) is not needed *at all*
* Ctrl-Shift-c to copy (e.g. URLs) in gnome-terminal
* Ctrl-Shift-v to paste in gnome-terminal
* Ctrl-c, Ctrl-v to copy and paste in graphical applications e.g. Firefox

**Comment by trallard** [comment]
Create repository and share with people
Need to push this to the RSE conference guys
