### ISSUE TITLE
Simplify getting started instructions

### ISSUE THREAD

**Issue by willfurnass** [trallard/JNB_reproducible#12]
The [Readme.md](Readme.md) doesn't currently provide a concise guide to what students need to do (i.e. things to copy and paste) and is too verbose and cluttered with facilitator setup notes.  

NB the setup could also be simplified by aliasing long command lines (#6)

**Comment by trallard** [comment]
Will separate this into attendees and instructor guidelines

**Comment by trallard** [comment]
Done by @willfurnass
